---
- hosts: win_db
  connection: local
  tasks:
  - name: Update Windows Servers
    ansible.windows.win_updates:
      category_names:
      - SecurityUpdates
      - CriticalUpdates
      reboot: no
      async: 360
      poll: 0
      register: Windows_updates

    - name: Check on Windows Updates
      async_status: jid={{Windows_updates.ansible_job_id}}
      register: job_result
      until: job_result.finished
      retries: 30

