---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Enable HA 
    vmware_cluster_ha:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      datacenter_name: "{{ datacenter }}"
      cluster_name: "{{ Cluster }}"
      enable_ha: True
      ha_vm_monitoring: vmMonitoringDisabled
      ha_host_monitoring: enabled
      slot_based_admission_control:
        failover_level: 1
    delegate_to: localhost

  - name: Enable DRS
    vmware_cluster_drs:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      datacenter_name: "{{ datacenter }}"
      cluster_name: "{{ Cluster }}"
      enable_drs: yes
    delegate_to: localhost