---
- name: 'CIS Domain 5'
  hosts: localhost
  become: yes
  tasks:
    - name: "4.1.1.1 Ensure auditd is installed"
      block:
        - name: "Install Audit"
          ansible.builtin.package:
            name: "{{item}}"
            state: present
          with_items:
            - audit
            - audit-libs
        - name: "Ensure audit is enabled"
          ansible.builtin.service:
            name: auditd
            state: started
            enabled: yes
        - name: "4.1.1.3 Ensure auditing for processes that start prior to auditd is enabled"
          ansible.builtin.replace:
            dest: /etc/default/grub
            regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit=1)(?:")'
            replace: '\1"\2 audit=1"'
            follow: yes
          ignore_errors: yes
          notify: generate new grub config

    - name: "4.1.2.1 Ensure audit log storage size is configured"
      ansible.builtin.lineinfile:
        path: /etc/audit/auditd.conf
        regexp: '^max_log_file ='
        line: 'max_log_file = 10'
        state: present
        create: yes
        mode: 0640
        owner: root
        group: root

    - name: "4.1.2.2 Ensure audit logs are not automatically deleted"
      ansible.builtin.lineinfile:
        path: /etc/audit/auditd.conf
        regexp: '^max_log_file_action ='
        line: 'max_log_file_action = keep_logs'
        state: present
        create: yes
        mode: 0640
        owner: root
        group: root

    - name: "4.1.2.3 Ensure audit system is set to single when the disk is full."
      ansible.builtin.lineinfile:
        path: /etc/audisp/audisp-remote.conf
        regexp: '^disk_full_action ='
        line: 'disk_full_action = single'
        state: present
        create: yes
        mode: 0640
        owner: root
        group: root

    - name: "SCORED | 4.1.1.2 | PATCH | Ensure system is disabled when audit logs are full"
      ansible.builtin.lineinfile:
        dest: /etc/audit/auditd.conf
        regexp: "^admin_space_left_action"
        line: "admin_space_left_action = halt"
        state: present

    - name: "SCORED | 4.1.1.2 | PATCH | Ensure system is disabled when audit logs are full"
      ansible.builtin.lineinfile:
        dest: /etc/audit/auditd.conf
        regexp: "^space_left_action"
        line: "space_left_action = email"
        state: present

    - name: "4.1.2.7 Ensure audit_backlog_limit is sufficient"
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX="audit_backlog_limit='
        line: 'GRUB_CMDLINE_LINUX="audit_backlog_limit=8192"'
        state: present
        create: yes
        mode: 0640
        owner: root
        group: root

    - name: "SCORED | 4.2.4 | PATCH | Ensure permissions on all logfiles are configured"
      command: find /var/log -type f -exec chmod g-wx,o-rwx {} +