---
- name: 'CIS Domain 5'
  hosts: localhost
  become: yes
  tasks:
    - name: Disable IPv6 on the instance
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AddressFamily inet'
        line: 'AddressFamily inet'
        state: present


    - name: Ensure IP forwarding is disabled
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv4.ip_forward = 0'
        line: 'net.ipv4.ip_forward = 0'
        state: present
        create: yes
        mode: 0644
        owner: root
        group: root

    - name: Ensure packet redirect sending is disabled
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv4.conf.all.send_redirects = 0'
        line: 'net.ipv4.conf.all.send_redirects = 0'
        state: present
        create: yes
        mode: 0644
        owner: root
        group: root

    - name: Run  net.ipv4.conf.all.send_redirects = 0
      ansible.builtin.shell: |
        sysctl -w net.ipv4.conf.all.send_redirects=0
        sysctl -w net.ipv4.conf.default.send_redirects=0
        sysctl -w net.ipv4.route.flush=1
