---
- hosts: localhost
  tasks:
  - name: Get vCenter Username & Password
    uri:
      url: http://{{ Vault_addr }}/v1/kv/vSphere/vCenter/Dev
      headers:
        X-Vault-Token: "{{ Token_key }}"
      validate_certs: false
    register: result_vcenter

  - name: Get ESXi Username & Password
    uri:
      url: http://{{ Vault_addr }}/v1/kv/vSphere/ESXi/Dev
      headers:
        X-Vault-Token: "{{ Token_key }}"
      validate_certs: false
    register: result_esxi

  - name: Add ESXi to vCenter
    community.vmware.vmware_host:
      validate_certs: no
      hostname:  result_vcenter.json.data.hostname
      username:  result_vcenter.json.data.username
      password:  result_vcenter.json.data.password
      datacenter: "{{ DC_Name }}"
      cluster: "{{ Cluster_Name }}"
      esxi_hostname: "{{ esxi_host }}"
      esxi_username: result_esxi.json.data.username
      esxi_password: result_esxi.json.data.password
      state: present
    delegate_to: localhost
    register: Result_DC

  - debug:
      var: Result_DC
