---
- hosts: localhost
  tasks:
  - name: Get vCenter Username & Password
    uri:
      url: http://{{ Vault_addr }}/v1/kv/vSphere/vCenter/Dev
      headers:
        X-Vault-Token: "{{ Token_key }}"
      validate_certs: false
    register: result_vcenter

  - name: Add ESXi to vCenter
    community.vmware.vmware_host:
      validate_certs: no
      hostname:  result_vcenter.json.data.hostname
      username:  result_vcenter.json.data.username
      password:  result_vcenter.json.data.password
      esxi_hostname: "{{ esxi_host }}"
      license: "{{ esxi_key }}"
      state: present
    delegate_to: localhost
    register: Result_DC

  - debug:
      var: Result_DC
